### ISSUE TITLE
Merge Datasets Together

### ISSUE THREAD

**Issue by MilaGargiulo** [daniellevb00/dPREP-project-team-3#17]

**Comment by daniellevb00** [comment]
I don't think we need to merge any datasets, just do our analysis for every city in Europe.

**Comment by MilaGargiulo** [comment]
Hey Daniëlle,

Ik had die aangemaakt omdat er stond dat dit moest gebeuren op de website
van Hannes. We moesten zo veel mogelijke specifieke issues maken tijdens de
lecture van vorige week, dus vandaar. Maar voel je vrij om toe te voegen en
verwijderen wat je wilt. Dit was gewoon puur om goed de les te volgen.

Groetjes Mila

Op wo 22 sep. 2021 om 10:59 schreef Daniëlle van Bruggen <
***@***.***>

**Comment by MilaGargiulo** [comment]
Eerste poging tot scrapen
